services:
  caddy:
    image: caddy:2
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    ports:
      - "80:80"
      - "443:443"
volumes:
  caddy_data:
