services:
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    ports:
      - 3000:3000
    restart: unless-stopped
